hopital_administration_homepage:
    path:     /accueil
    defaults: { _controller: HopitalAdministrationBundle:Default:index }
hopital_administration_viewPatient:
    path:     /patient
    defaults: { _controller: HopitalAdministrationBundle:Default:patient }
hopital_administration_newpatient:
    path:     /newpatient
    defaults: { _controller: HopitalAdministrationBundle:Default:newpatient }
hopital_administration_modifPatient:
    path:     /modifPatient
    defaults: { _controller: HopitalAdministrationBundle:Default:modifPatient }
hopital_administration_newsejour:
    path:     /newsejour
    defaults: { _controller: HopitalAdministrationBundle:Default:newsejour }
hopital_administration_viewsejour:
    path:     /viewsejour
    defaults: { _controller: HopitalAdministrationBundle:Default:viewsejour }
hopital_administration_modifSejour:
    path:     /modifSejour
    defaults: { _controller: HopitalAdministrationBundle:Default:modifSejour }
hopital_administration_suppPatient:
    path:     /suppPatient
    defaults: { _controller: HopitalAdministrationBundle:Default:suppPatient }
hopital_administration_suppSejour:
    path:     /suppSejour
    defaults: { _controller: HopitalAdministrationBundle:Default:suppSejour }
hopital_administration_viewService:
    path:     /service
    defaults: { _controller: HopitalAdministrationBundle:Default:service }
