hopital_administration_homepage:
    path:     /accueil
    defaults: { _controller: HopitalAdministrationBundle:Default:index }
hopital_administration_viewPatient:
    path:     /patient
    defaults: { _controller: HopitalAdministrationBundle:Default:patient }
hopital_administration_newpatient:
    path:     /newpatient
    defaults: { _controller: HopitalAdministrationBundle:Default:newpatient }
hopital_administration_modifPatient:
    path:     /modifPatient
    defaults: { _controller: HopitalAdministrationBundle:Default:modifPatient }
hopital_administration_newsejour:
    path:     /newsejour
    defaults: { _controller: HopitalAdministrationBundle:Default:newsejour }
hopital_administration_viewsejour:
    path:     /viewsejour
    defaults: { _controller: HopitalAdministrationBundle:Default:viewsejour }
hopital_administration_modifSejour:
    path:     /modifSejour
    defaults: { _controller: HopitalAdministrationBundle:Default:modifSejour }
hopital_administration_suppPatient:
    path:     /suppPatient
    defaults: { _controller: HopitalAdministrationBundle:Default:suppPatient }
hopital_administration_suppSejour:
    path:     /suppSejour
    defaults: { _controller: HopitalAdministrationBundle:Default:suppSejour }
hopital_administration_viewService:
    path:     /service
    defaults: { _controller: HopitalAdministrationBundle:Default:service }
hopital_administration_modifService:
    path:     /modifService
    defaults: { _controller: HopitalAdministrationBundle:Default:modifService }
hopital_administration_suppService:
    path:     /suppService
    defaults: { _controller: HopitalAdministrationBundle:Default:suppService }
hopital_administration_newservice:
    path:     /newservice
    defaults: { _controller: HopitalAdministrationBundle:Default:newservice }
hopital_administration_newChambre:
    path:     /newChambre
    defaults: { _controller: HopitalAdministrationBundle:Default:newChambre }
hopital_administration_viewChambre:
    path:     /viewChambre
    defaults: { _controller: HopitalAdministrationBundle:Default:Chambre }
hopital_administration_modifChambre:
    path:     /modifChambre
    defaults: { _controller: HopitalAdministrationBundle:Default:modifChambre }
hopital_administration_suppChambre:
    path:     /suppChambre
    defaults: { _controller: HopitalAdministrationBundle:Default:suppChambre }
login:
  path: /login
  defaults: { _controller: HopitalAdministrationBundle:Security:login }

login_check:
  path: /login_check

logout:
  path: /logout
  defaults: { _controller: HopitalAdministrationBundle:Security:logout }
